version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01

    environment:
      BASE_REV: << pipeline.git.base_revision >>
      CURR_REV: << pipeline.git.revision >>

    steps:
      - add_ssh_keys:
          fingerprints:
            - "49:f4:fc:ad:62:47:a9:97:45:0f:ca:e3:dd:08:cd:93"
            - "d9:e4:6a:a5:77:79:65:a7:d7:50:8d:14:18:a6:48:91"
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install texlive texlive-latex-extra texlive-fonts-extra ghostscript
            pip install lxml
      - run:
          name: Change ImageMagick policy
          command: |
            sudo chmod o+w /etc/ImageMagick-6/policy.xml
            python change_policy.py
      - run:
          name: Compile latex to pdf and generate png preview and push back changes
          command: |
            if git diff --name-only $BASE_REV..$CURR_REV | grep -E "profile.*|resume.tex" &> /dev/null;
            then
              pdflatex resume.tex
              convert -density 250 -flatten resume.pdf[0] -quality 100 resume.png
              if ! git diff-index --quiet HEAD --; then
                git config --global user.name "CircleCI"
                git remote set-url origin $CIRCLE_REPOSITORY_URL &> /dev/null
                git add -u
                git commit -m "Update pdf and png preview ${CIRCLE_BUILD_URL} [ci skip]"
                git pull --rebase
                git push origin HEAD:${CIRCLE_BRANCH}

                git clone git@github.com:AleksaC/personal-website.git
                cp resume.pdf personal-website/static
                cd personal-website
                git add -u
                git commit -m "Update resume"
                git pull --rebase
                git push origin HEAD
              fi
            fi

workflows:
  version: 2
  main:
    jobs:
      - build
